name: AI Code Review
on: [pull_request]
jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run CodeRabbit
        uses: coderabbitai/coderabbit-action@v1
        with:
          openai_api_key: ${{ secrets.OPENAI_API_KEY }}
